### ISSUE TITLE
test on  yosemite

### ISSUE THREAD

**Issue by Shu-HowTing** [xuyanwu/RAL-Net#1]
Hello,thank you for your sharing!
I trained the model on `liberty`  and  tested on `notredame` successfully. But the following bug appears when i try to `create test_loaders` with `yosemite` dataset :
```
RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at ..\aten\src\TH\THGeneral.cpp:188
```

**Comment by xuyanwu** [comment]
Maybe try to decrease the num_worker in dataloader.  The code runs fine in my sever. Good luck!

**Comment by Shu-HowTing** [comment]
OK，I will have a try!Thanks !






On 3/6/2019 13:47，yanwu xu<notifications@github.com> wrote：

Maybe try to decrease the num_worker in dataloader. The code runs fine in my sever. Good luck!
